import {mountSecurity,twoFactorScreen,recoveryScreen} from './security-ui.js';
import {apiFetch} from './api-config.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function authRequest(path,{method='GET',body}={}){
  const response=await apiFetch(path,{method,signal:AbortSignal.timeout(15000),headers:body?{'Content-Type':'application/json','X-Bandbook-Request':'1'}:{},...(body?{body:JSON.stringify(body)}:{})});
  const payload=await response.json();if(!response.ok){const error=Error(payload.error||'Request failed.');error.status=response.status;error.payload=payload;throw error;}return payload;
}
// mode: setup (first run, makes the Owner), register, or login. onBack returns to the calculator.
export function loginScreen(session,onSuccess,mode=session.setupRequired?'setup':'login',onBack=null){
  const setup=mode==='setup',creating=mode!=='login';
  document.querySelector('#app').innerHTML=`<main class="auth-shell"><section class="auth-card auth-entry">${onBack&&!setup?'<button type="button" class="text-button auth-back" id="auth-back">← Back to the calculator</button>':''}<div class="auth-brand"><img class="auth-logo" src="./logo.svg" alt=""><span><strong>Band Calculator</strong><small>Count it, save it, cash it out</small></span></div><h1>${setup?'Create the Owner account':creating?'Create your account':'Welcome back'}</h1><p>${setup?'One-time setup. The Owner is the only account that can change band prices.':creating?'Free and instant. Your counts, running total and history get saved to your account.':'Sign in to save counts and see your history.'}</p><form id="auth-form"><label for="auth-username">Username</label><input id="auth-username" name="username" required minlength="${creating?3:1}" maxlength="32" autocapitalize="none" spellcheck="false" autocomplete="username" ${creating?'pattern="[A-Za-z0-9_.\\-]{3,32}"':''}>${creating?'<small>3–32 letters, numbers, dots, dashes or underscores.</small>':''}<label for="auth-password">Password</label><div class="auth-password-field"><input id="auth-password" name="password" type="password" required minlength="${creating?12:1}" maxlength="128" autocomplete="${creating?'new-password':'current-password'}"><button type="button" id="auth-show-password" class="password-visibility" aria-label="Show password" aria-controls="auth-password" aria-pressed="false"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/><path class="eye-slash" d="m3 3 18 18"/></svg></button></div>${creating?'<small>12+ characters. Nobody can look it up, so pick one you will remember.</small>':''}<label class="remember-login"><input id="auth-remember" type="checkbox" checked><span>Keep me signed in<small>Up to 30 days. Turn off on shared devices.</small></span></label><div id="auth-error" class="form-error" role="alert"></div><button class="button primary" type="submit">${setup?'Create Owner account':creating?'Create account':'Sign in'}</button></form><div class="auth-links">${!setup?`<div class="auth-switch"><span>${creating?'Already have an account?':'New here?'}</span><button class="text-button" type="button" id="auth-switch">${creating?'Sign in':'Create an account'}</button></div>`:''}${!creating?'<button class="text-button security-back" type="button" id="auth-recover">Trouble signing in?</button>':''}</div><div class="auth-footnote">${session.development?'Local development preview':'No account needed to use the calculator'}</div></section></main>`;
  document.querySelector('#auth-back')?.addEventListener('click',onBack);
  document.querySelector('#auth-switch')?.addEventListener('click',()=>loginScreen(session,onSuccess,creating?'login':'register',onBack));
  document.querySelector('#auth-recover')?.addEventListener('click',()=>recoveryScreen(authRequest,()=>loginScreen(session,onSuccess,'login',onBack)));
  document.querySelector('#auth-show-password').onclick=event=>{const button=event.currentTarget,input=document.querySelector('#auth-password'),visible=input.type==='password';input.type=visible?'text':'password';button.setAttribute('aria-pressed',String(visible));button.setAttribute('aria-label',visible?'Hide password':'Show password');};
  document.querySelector('#auth-username').focus();
  const form=document.querySelector('#auth-form');form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button[type="submit"]');if(button.disabled)return;const label=button.textContent;button.disabled=true;button.textContent=creating?'Creating…':'Signing in…';form.setAttribute('aria-busy','true');document.querySelector('#auth-error').textContent='';try{const result=await authRequest('/api/auth/'+(setup?'setup':creating?'register':'login'),{method:'POST',body:{username:document.querySelector('#auth-username').value,password:document.querySelector('#auth-password').value,remember:document.querySelector('#auth-remember').checked}});if(result.mfaRequired){twoFactorScreen(result,onSuccess,authRequest,()=>loginScreen(session,onSuccess,'login',onBack));return;}await onSuccess(result);}catch(error){document.querySelector('#auth-error').textContent=error.message;button.disabled=false;button.textContent=label;}finally{form.removeAttribute('aria-busy');}};
}
export function accountDialog(user,openModal,onSessionChange){
  openModal(`<form class="account-profile-summary" id="account-name-form"><h2>${esc(user.name)}</h2><p>@${esc(user.username)} · ${user.owner?'Owner':'Member'}</p><label for="account-name">Display name</label><div class="account-name-row"><input id="account-name" maxlength="60" required value="${esc(user.name)}"><button class="button secondary" type="submit">Save</button></div><p class="form-error" id="account-name-error" role="alert"></p></form><div id="account-security-panel"></div>`);
  const form=document.querySelector('#account-name-form');
  form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await authRequest('/api/account/name',{method:'POST',body:{name:form.querySelector('#account-name').value}});if(onSessionChange)await onSessionChange();document.querySelector('#modal').close();}catch(error){form.querySelector('#account-name-error').textContent=error.message;}finally{button.disabled=false;}};
  mountSecurity(document.querySelector('#account-security-panel'),{request:authRequest,user,onDone:async()=>{if(onSessionChange)await onSessionChange();document.querySelector('#modal').close();}});
}
